services:
  - type: web
    name: selah-backend
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start:prod
    rootDir: .
    envVars:
      - key: JWT_SECRET
        value: "secretKey"
      - key: DATABASE_URL
        value: "postgresql://selahdb_kpo2_user:SLNNnCMpmYvEkD8FxDWpkhxS499JZM90@dpg-d0o52jvdiees739mi9q0-a.oregon-postgres.render.com:5432/selahdb_kpo2?schema=public"
      - key: RESOURCE_FOLDER_LOCATION
        value: "./public/images"
      - key: RESOURCE_DOMAIN
        value: "https://selah-backend.onrender.com/api"
      - key: RESOURCE_IMAGE_PREFIX
        value: "https://selah-backend.onrender.com/images"
      - key: MAX_FILE_SIZE
        value: "5242880"
