services:
  - type: web
    name: selah-backend
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start:prod
    rootDir: .
    envVars:
      - key: PORT
        value: "3000"
    
