services:
  - type: web
    name: selah-backend
    runtime: node
    plan: free
    buildCommand: ./node_modules/.bin/nest build
    startCommand: npm run start:prod
    rootDir: .
    envVars:
      - key: JWT_SECRET
        value: "secretKey"
      - key: DATABASE_URL
        value: "postgresql://postgres:test@localhost:5432/back_end?schema=public"
      - key: RESOURCE_FOLDER_LOCATION
        value: "./public/images"
      - key: RESOURCE_DOMAIN
        value: "https://selah-backend.onrender.com/api"
      - key: RESOURCE_IMAGE_PREFIX
        value: "https://selah-backend.onrender.com/images"
      - key: MAX_FILE_SIZE
        value: "5242880"
